"""Visualization helpers for publication-ready figures."""

from .plot_settings import (
    BASE_STYLE,
    BW_COLORS,
    BW_EDGES,
    BW_FILLS,
    BW_HATCHES,
    BW_LINESTYLES,
    BW_MARKERS,
    BW_STYLE,
    COMPARISON_STYLE,
    DEFAULT_FIGURE_DIR,
    WIDE_STYLE,
    PlotStyle,
    apply_plot_style,
    bw_errorbar_style,
    bw_fill_style,
    bw_series_style,
    configure_axes,
    create_figure,
    figure_path,
    save_figure,
)

__all__ = [
    "BASE_STYLE",
    "BW_COLORS",
    "BW_EDGES",
    "BW_FILLS",
    "BW_HATCHES",
    "BW_LINESTYLES",
    "BW_MARKERS",
    "BW_STYLE",
    "COMPARISON_STYLE",
    "DEFAULT_FIGURE_DIR",
    "WIDE_STYLE",
    "PlotStyle",
    "apply_plot_style",
    "bw_errorbar_style",
    "bw_fill_style",
    "bw_series_style",
    "configure_axes",
    "create_figure",
    "figure_path",
    "save_figure",
]
